### ISSUE TITLE
.gitmodules urls

### ISSUE THREAD

**Issue by crshrprt** [a-n-t-h-o-n-y/XenSequencer#2]
The .gitmodules file contains, for most submodules, urls in the form of `git@github.com:...` instead of `https://github.com/...`.
This leads to errors when doing `git submodule update --init --recursive` or `git clone --recurse-submodules ...`.

Changing all the submodules urls to `https://github.com/...` solves this issue:

```
[submodule "external/MicrotonalStepSequencer"]
	path = external/MicrotonalStepSequencer
	url = https://github.com/a-n-t-h-o-n-y/MicrotonalStepSequencer.git
[submodule "external/JUCE"]
	path = external/JUCE
	url = https://github.com/juce-framework/JUCE.git
[submodule "external/signals-light"]
	path = external/signals-light
	url = https://github.com/a-n-t-h-o-n-y/signals-light.git
[submodule "external/yaml-cpp"]
	path = external/yaml-cpp
	url = https://github.com/jbeder/yaml-cpp
[submodule "external/json"]
	path = external/json
	url = https://github.com/nlohmann/json.git
[submodule "external/Catch2"]
	path = external/Catch2
	url = https://github.com/catchorg/Catch2.git
```

**Comment by a-n-t-h-o-n-y** [comment]
I've updated it to use relative paths (b672947). This will use the same protocol that XenSequencer is cloned with to grab the submodules.
